export declare const MAX_SAFE_INTEGER = 9007199254740991;
export declare const NUMERIC_REGEX: RegExp;
export declare const LEFT_RIGHT_WHITESPACE_REGEX: RegExp;
export declare const LEFT_RIGHT_DOT_REGEX: RegExp;
export declare const BRACKETED_REGEX: RegExp;
export declare const OCTAL_REGEX: RegExp;
export declare const BAD_HEX_REGEX: RegExp;
export declare const BINARY_REGEX: RegExp;
export declare const WORD_SEPARATOR_REGEX: RegExp;
export declare const UPPERCASE_CHARACTER_REGEX: RegExp;
export declare const LEFT_RIGHT_NONALPHANUM_REGEX: RegExp;
export declare const LOWER_UPPER_PAIR_REGEX: RegExp;
export declare const NONALPHANUM_OR_UNDERSCORE_REGEX: RegExp;
export declare const arrayLikes: Set<string>;
export declare const mapLikes: Set<string>;
